name: CI
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true
      
    - name: Build Docker Image
      run:  docker build -t n64sdk https://github.com/CrashOveride95/n64sdkmod.git
    
    - name: Build
      run: docker run --name n64sdk-instance -e N64_LIBGCCDIR="/usr/local/n64chain/lib/gcc/mips64-elf/10.2.0" -e DEBIAN_FRONTEND="noninteractive" -v "${{ github.workspace }}":/opt/src n64sdk /opt/src/compile_docker.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: shibagame
        path: build/*.n64

    - name: Cleanup
      run: docker rm n64sdk-instance
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Test Env
        run: |
          sudo apt install -y xvfb mupen64plus wget unzip
          wget https://cen64.com/uploads/stable/cen64-debian9-x86_64
          wget https://www.dropbox.com/sh/i0klk7ytso6homa/AACL4NiXIauDH6uRbdwBL7mha/N64%20BIOS.zip?dl=0
          unzip N64\ Bios.zip
          chmod +x cen64-debian9-x86_64
          Xvfb :100 &
          export DISPLAY=:100

      - name: test-cen64
        run: echo "Test with Cen64 here"
        
      - name: test-mupen64
        run: echo "Test with Mupen64 here"